apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kalmanguard

resources:
  - namespace.yaml
  - agents-deployment.yaml
  - kalman-deployment.yaml
  - frontend-deployment.yaml
  - redis-deployment.yaml
  - services.yaml
  - configmap.yaml
  - secrets.yaml

configMapGenerator:
  - name: kalmanguard-config
    envs:
      - config.env

secretGenerator:
  - name: kalmanguard-secrets
    envs:
      - secrets.env
